//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_EntityFramework_Statistics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_3_20ProjectsEntities : DbContext
    {
        public DB_3_20ProjectsEntities()
            : base("name=DB_3_20ProjectsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<TBLcustomer> TBLcustomer { get; set; }
        public virtual DbSet<TBLorder> TBLorder { get; set; }
        public virtual DbSet<TBLproduct> TBLproduct { get; set; }
    }
}
