//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_EntityFramework_Statistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLcustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLcustomer()
        {
            this.TBLorder = new HashSet<TBLorder>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_country { get; set; }
        public string customer_city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLorder> TBLorder { get; set; }
    }
}
