//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_EntityFramework_Statistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLorder
    {
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Totalprice { get; set; }
    
        public virtual TBLcustomer TBLcustomer { get; set; }
        public virtual TBLproduct TBLproduct { get; set; }
    }
}
