//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3_EntityFramework_Statistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLproduct()
        {
            this.TBLorder = new HashSet<TBLorder>();
        }
    
        public int productId { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_stock { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<bool> product_status { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLorder> TBLorder { get; set; }
    }
}
