//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project19_TableStatusMomentary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_table
    {
        public int table_id { get; set; }
        public string table_number { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
