//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2_EntityFrameworkProduct_DBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int Product_id { get; set; }
        public string Product_name { get; set; }
        public Nullable<int> Product_stock { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
