//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project11_TriggerOrderStock.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int orderid { get; set; }
        public string customer { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> totalprice { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
