//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project18_SuperStoreDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class superstore
    {
        public string Category { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<byte> Discount { get; set; }
        public string Market { get; set; }
        public byte 记录数 { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Order_ID { get; set; }
        public string Order_Priority { get; set; }
        public string Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<double> Profit { get; set; }
        public byte Quantity { get; set; }
        public string Region { get; set; }
        public int Row_ID { get; set; }
        public short Sales { get; set; }
        public string Segment { get; set; }
        public System.DateTime Ship_Date { get; set; }
        public string Ship_Mode { get; set; }
        public double Shipping_Cost { get; set; }
        public string State { get; set; }
        public string Sub_Category { get; set; }
        public short Year { get; set; }
        public string Market2 { get; set; }
        public byte weeknum { get; set; }
    }
}
